In [2]:
import pandas as pd
import numpy as np
import proMAD

In [4]:
raw_data = pd.read_excel('raw_data-xlsx/merged_data.xlsx')

In [5]:
raw_data.head()

,Column1,Block,Column,Row,Name,ID,X,Y,Dia.,F532 Median,...,F532 Mean - B532,F635 Mean - B635,F532 Total Intensity,F635 Total Intensity,SNR 532,SNR 635,Flags,Normalize,Autoflag,Source_file
0,0,1,1,1,S1_0.1_T,1D1,8220,5560,180,679,...,445,67,159734,57140,3.884,3.706,0,0,0,1
1,1,1,2,1,S1_0.1_S,1A1,8540,5530,220,1007,...,732,443,358413,235214,6.301,9.149,0,0,0,1
2,2,1,3,1,S1_0.25_S,1C5,8890,5540,200,1159,...,888,598,340012,239506,8.947,9.914,0,0,0,1
3,3,1,4,1,S1_0.5_S,1B5,9250,5540,210,1019,...,795,796,309917,301091,8.860,18.093,0,0,0,1
4,4,1,5,1,S1_0.1_B,1C1,9620,5530,160,1195,...,982,132,242514,59695,18.635,6.300,0,0,0,1

In [6]:
KEEP = ['Source_file','Block', 'Column', 'Row', 'Name', 'ID', 'F532 Median',
       'B532 Median', 'F635 Median', 'B635 Median', 'F532 Median - B532',
       'F635 Median - B635', 'F532 Total Intensity', 'F635 Total Intensity', 'SNR 532', 'SNR 635']

In [7]:
RAW_data = raw_data[KEEP]

In [8]:
RAW_data.head()

,Source_file,Block,Column,Row,Name,ID,F532 Median,B532 Median,F635 Median,B635 Median,F532 Median - B532,F635 Median - B635,F532 Total Intensity,F635 Total Intensity,SNR 532,SNR 635
0,1,1,1,1,S1_0.1_T,1D1,679,179,219,156,500,63,159734,57140,3.884,3.706
1,1,1,2,1,S1_0.1_S,1A1,1007,182,652,157,825,495,358413,235214,6.301,9.149
2,1,1,3,1,S1_0.25_S,1C5,1159,188,848,160,971,688,340012,239506,8.947,9.914
3,1,1,4,1,S1_0.5_S,1B5,1019,186,1024,157,833,867,309917,301091,8.860,18.093
4,1,1,5,1,S1_0.1_B,1C1,1195,184,290,155,1011,135,242514,59695,18.635,6.300

In [25]:
F532 Median - B532

,Block,Column,Row,Name,ID,F532 Median,B532 Median,F635 Median,B635 Median,F532 Median - B532,F635 Median - B635,F532 Total Intensity,F635 Total Intensity,SNR 532,SNR 635
0,1,1,1,S1_0.1_T,1D1,679,179,219,156,500,63,159734,57140,3.884,3.706
1,1,2,1,S1_0.1_S,1A1,1007,182,652,157,825,495,358413,235214,6.301,9.149
2,1,3,1,S1_0.25_S,1C5,1159,188,848,160,971,688,340012,239506,8.947,9.914
3,1,4,1,S1_0.5_S,1B5,1019,186,1024,157,833,867,309917,301091,8.860,18.093
4,1,5,1,S1_0.1_B,1C1,1195,184,290,155,1011,135,242514,59695,18.635,6.300

,Block,Column,Row,Name,ID,F532 Median,B532 Median,F635 Median,B635 Median,F532 Median - B532,F635 Median - B635,F532 Total Intensity,F635 Total Intensity,SNR 532,SNR 635
22,1,23,1,N-protein_0.5_S,1C7,16585,197,772,156,16388,616,4339386,221850,89.338,20.654
54,1,23,2,N-protein_0.5_S,1C7,16483,207,780,156,16276,624,4422702,222635,114.617,24.636
86,1,23,3,N-protein_0.5_S,1C7,15365,205,758,156,15160,602,4190764,216190,85.697,3.772
118,1,23,4,N-protein_0.5_S,1C7,15814,206,741,156,15608,585,4272879,209777,57.665,15.061
406,2,23,1,N-protein_0.5_S,1C7,58715,289,8718,258,58426,8460,14917726,2291237,24.303,26.091
438,2,23,2,N-protein_0.5_S,1C7,48691,323,7382,257,48368,7125,15619321,2355118,21.446,23.475
470,2,23,3,N-protein_0.5_S,1C7,57657,298,8431,254,57359,8177,15194607,2196872,33.247,34.609
502,2,23,4,N-protein_0.5_S,1C7,51727,282,7583,238,51445,7345,15876408,2342037,47.255,41.926
790,3,23,1,N-protein_0.5_S,1C7,48568,200,5036,182,48368,4854,15224776,1813586,354.330,130.441
822,3,23,2,N-protein_0.5_S,1C7,54393,223,6139,185,54170,5954,14874558,1657587,624.387,64.731
854,3,23,3,N-protein_0.5_S,1C7,56015,245,6279,189,55770,6090,14931676,1703309,671.314,136.632
886,3,23,4,N-protein_0.5_S,1C7,57390,238,6305,189,57152,6116,12925893,1349053,440.561,44.412
1174,4,23,1,N-protein_0.5_S,1C7,49711,208,3174,160,49503,3014,15938188,995663,652.210,29.259
1206,4,23,2,N-protein_0.5_S,1C7,50283,220,2940,161,50063,2779,16055940,940210,57.455,9.338
1238,4,23,3,N-protein_0.5_S,1C7,49411,222,2817,160,49189,2657,15276861,904344,71.816,15.128
1270,4,23,4,N-protein_0.5_S,1C7,53060,219,2982,158,52841,2824,13202032,798761,60.772,14.261
1558,5,23,1,N-protein_0.5_S,1C7,13515,206,1214,162,13309,1052,3745124,346568,179.046,34.370
1590,5,23,2,N-protein_0.5_S,1C7,13832,214,1191,161,13618,1030,3236836,280359,170.110,25.667
1622,5,23,3,N-protein_0.5_S,1C7,11605,210,995,161,11395,834,3213982,283680,191.423,28.038
1654,5,23,4,N-protein_0.5_S,1C7,12092,204,1004,161,11888,843,3291675,294033,98.106,16.191
1942,6,23,1,N-protein_0.5_S,1C7,21476,204,2091,155,21272,1936,7310337,648108,58.313,41.444
1974,6,23,2,N-protein_0.5_S,1C7,21271,216,1902,155,21055,1747,7075376,595244,116.458,48.464
2006,6,23,3,N-protein_0.5_S,1C7,24721,210,1942,156,24511,1786,6935681,522741,571.816,57.423
2038,6,23,4,N-protein_0.5_S,1C7,24993,206,1973,156,24787,1817,6960927,559582,24.479,20.831
2326,7,23,1,N-protein_0.5_S,1C7,49107,232,17275,168,48875,17107,16500074,6476068,94.527,272.250
2358,7,23,2,N-protein_0.5_S,1C7,39724,227,9321,164,39497,9157,13316261,3937898,602.393,308.531
2390,7,23,3,N-protein_0.5_S,1C7,43486,214,10102,164,43272,9938,11216956,3256364,371.242,316.625
2422,7,23,4,N-protein_0.5_S,1C7,34378,206,6484,161,34172,6323,11544300,3294779,487.250,109.733
2710,8,23,1,N-protein_0.5_S,1C7,501,338,365,161,163,204,127004,94846,0.452,2.108
2742,8,23,2,N-protein_0.5_S,1C7,546,330,409,161,216,248,85150,63812,4.733,7.212
2774,8,23,3,N-protein_0.5_S,1C7,514,315,396,161,199,235,80210,61264,4.829,6.727
2806,8,23,4,N-protein_0.5_S,1C7,506,331,349,161,175,188,148565,93224,5.568,10.368
3094,9,23,1,N-protein_0.5_S,1C7,50170,224,2731,177,49946,2554,15808115,952103,147.265,53.381
3126,9,23,2,N-protein_0.5_S,1C7,58949,229,3270,176,58720,3094,14953015,889181,480.357,90.724
3158,9,23,3,N-protein_0.5_S,1C7,58649,225,3239,174,58424,3065,15083724,865749,552.244,88.207
3190,9,23,4,N-protein_0.5_S,1C7,47825,232,2574,172,47593,2402,15271173,887698,383.248,74.464
3478,10,23,1,N-protein_0.5_S,1C7,756,168,304,160,588,144,188673,78000,40.500,0.406
3510,10,23,2,N-protein_0.5_S,1C7,721,168,305,160,553,145,178025,77005,37.429,6.381
3542,10,23,3,N-protein_0.5_S,1C7,740,169,289,160,571,129,179503,75139,21.120,2.551
3574,10,23,4,N-protein_0.5_S,1C7,677,168,279,160,509,119,167330,73522,34.500,6.368
3862,11,23,1,N-protein_0.5_S,1C7,292,222,512,732,70,-220,93073,177170,2.414,-0.873
3894,11,23,2,N-protein_0.5_S,1C7,308,222,522,736,86,-214,97118,177935,3.037,-0.946
3926,11,23,3,N-protein_0.5_S,1C7,310,218,506,712,92,-206,79567,133760,3.214,-1.075
3958,11,23,4,N-protein_0.5_S,1C7,305,217,531,682,88,-151,97773,175121,2.444,-0.727
4246,12,23,1,N-protein_0.5_S,1C7,1704,176,338,157,1528,181,489282,106364,85.625,10.294
4278,12,23,2,N-protein_0.5_S,1C7,1795,177,356,158,1618,198,421093,91235,91.625,10.667
4310,12,23,3,N-protein_0.5_S,1C7,1766,176,352,157,1590,195,412933,88939,89.625,10.824
4342,12,23,4,N-protein_0.5_S,1C7,1732,175,357,157,1557,200,416394,89089,72.450,5.229
4630,13,23,1,N-protein_0.5_S,1C7,218,177,219,154,41,65,56351,57621,2.353,5.154
4662,13,23,2,N-protein_0.5_S,1C7,228,180,216,154,48,62,58519,57078,2.706,5.000
4694,13,23,3,N-protein_0.5_S,1C7,232,178,228,154,54,74,48827,49173,3.056,6.500
4726,13,23,4,N-protein_0.5_S,1C7,228,181,222,155,47,67,59272,58920,2.722,4.733
5014,14,23,1,N-protein_0.5_S,1C7,390,175,413,159,215,254,98767,103343,13.063,12.579
5046,14,23,2,N-protein_0.5_S,1C7,399,174,450,158,225,292,81031,92360,10.095,14.684
5078,14,23,3,N-protein_0.5_S,1C7,384,174,388,158,210,230,97417,105089,10.789,12.350
5110,14,23,4,N-protein_0.5_S,1C7,390,172,394,157,218,237,95980,99599,13.333,14.188

array(['S1_0.1_T', 'S1_0.1_S', 'S1_0.25_S', 'S1_0.5_S', 'S1_0.1_B',
       'S1_0.25_B', 'S1_0.5_B', 'S-RBD_0.5_Y', 'S-RBD_0.25_S',
       'S-RBD_0.5_S', 'S2-1_0.05_T', 'S2-2_0.1_T', 'N-protein_0.1_T',
       'N-protein_0.05_K', 'N-protein_0.1_K', 'N-protein_0.2_K', 'buffer',
       'N-protein_0.1_W', 'N-protein_0.25_W', 'N-protein_0.5_W',
       'N-protein_0.1_S', 'N-protein_0.25_S', 'N-protein_0.5_S',
       'N-Cter_0.1_K', 'N-Cter_0.25_K', 'N-Cter_0.5_K', 'N-Nter_0.1_K',
       'N-Nter_0.25_K', 'N-Nter_0.5_K', 'NSP2_0.05_K', 'NSP2_0.1_K',
       'NSP2_0.25_K', 'E-protein_0.25_T', 'E-protein_0.1_K',
       'E-protein_0.25_K', 'E-protein_0.5_K', 'NSP1_0.1_T', 'NSP1_0.1_K',
       'NSP1_0.25_K', 'NSP1_0.5_K', 'NSP4_0.1_T', 'NSP5_0.1_T',
       'NSP5_0.25_T', 'NSP5_0.5_T', 'NSP5_0.1_K', 'NSP5_0.25_K',
       'NSP5_0.5_K', 'NSP7_0.1_T', 'NSP8_0.25_T', 'NSP8_0.1_K',
       'NSP8_0.25_K', 'NSP8_0.5_K', 'NSP9_0.25_T', 'NSP9_0.1_K',
       'NSP9_0.25_K', 'NSP9_0.5_K', 'NSP10_0.1_T', 'NSP10_0.2_T',
       'NSP10_0.3_T', 'NSP10_0.1_K', 'NSP10_0.25_K', 'NSP10_0.5_K',
       'S1-4_0.2_K', 'NSP14_0.05_K', 'NSP14_0.1_K', 'NSP14_0.25_K',
       'NSP15_0.1_T', 'NSP15_0.1_K', 'NSP15_0.25_K', 'NSP15_0.5_K',
       'NSP16_0.1_T', 'NSP16_0.1_K', 'NSP16_0.25_K', 'NSP16_0.5_K',
       'ORF6_0.1_T', 'ORF7b_0.1_T', 'ORF9b_0.1_T', 'GST_0.1_',
       'AGR2-biotin', 'EGFP_0.1_K', 'EGFP_0.25_K', 'eGFP_0.5_K',
       'ACE2-Fc_0.25_S', 'ACE2-Fc_0.5_S', 'ACE2_0.5_S', 'UBE2D3-His',
       'H-IgG', 'H-IgM', 'Anti-H-IgG_0.025', 'Anti-H-IgG_0.1',
       'Anti-H-IgM_0.025', 'Anti-H-IgM_0.1', 'Cy5', 'Cy3'], dtype=object)

0       100
1       100
2       100
3       100
4       100
       ...
5371    100
5372    100
5373    100
5374    100
5375    100
Name: Circularity, Length: 5376, dtype: int64

In [35]:
raw_data4.head()

,Block,Column,Row,Name,ID,X,Y,Dia.,F532 Median,F532 Mean,...,F635 Median - B635,F532 Mean - B532,F635 Mean - B635,F532 Total Intensity,F635 Total Intensity,SNR 532,SNR 635,Flags,Normalize,Autoflag
0,1,1,1,S1_0.1_T,1D1,8830,5570,160,430,428,...,3,273,6,88981,32574,30.111,0.625,0,0,0
1,1,2,1,S1_0.1_S,1A1,9120,5540,190,154,157,...,19,3,26,40174,45039,0.250,3.429,0,0,0
2,1,3,1,S1_0.25_S,1C5,9460,5560,170,157,160,...,75,7,82,33262,48312,0.625,10.000,0,0,0
3,1,4,1,S1_0.5_S,1B5,9840,5560,180,165,168,...,220,15,220,42959,94660,1.625,24.222,0,0,0
4,1,5,1,S1_0.1_B,1C1,10230,5550,180,203,207,...,2,53,6,52893,40031,5.778,0.625,0,0,0

In [36]:
raw_data2.head()

,Block,Column,Row,Name,ID,X,Y,Dia.,F532 Median,F532 Mean,...,F635 Median - B635,F532 Mean - B532,F635 Mean - B635,F532 Total Intensity,F635 Total Intensity,SNR 532,SNR 635,Flags,Normalize,Autoflag
0,1,1,1,S1_0.1_T,1D1,8330,5470,170,928,892,...,90,717,95,185578,51718,39.611,7.077,0,0,0
1,1,2,1,S1_0.1_S,1A1,8670,5490,200,807,743,...,332,567,323,234729,150763,10.615,13.739,0,0,0
2,1,3,1,S1_0.25_S,1C5,9040,5470,200,848,826,...,483,646,466,260898,196441,6.598,13.727,0,0,0
3,1,4,1,S1_0.5_S,1B5,9410,5460,200,730,676,...,641,498,549,213746,222309,5.459,17.933,0,0,0
4,1,5,1,S1_0.1_B,1C1,9770,5470,170,1147,1115,...,115,939,117,231994,56292,18.480,7.000,0,0,0